using System.ComponentModel.DataAnnotations;

namespace WoodseatsScouts.Coins.Api.Models.Domain;

public class Coin
{
    public int Id { get; set; }
    
    public int ActivityBaseSequenceNumber { get; set; }
    
    public int ActivityBaseId { get; set; }
    
    public ActivityBase? ActivityBase { get; set; }

    public int Value { get; set; }

    /// <summary>
    /// Autogenerated externally before going live, unlike Member's code which is computed as members can be added after app is live.
    /// </summary>
    [StringLength(16)]
    public string Code { get; set; } = null!;

    public int? MemberId { get; set; }
    
    public ScoutMember? Member { get; set; }
    
    public DateTime? LockUntil { get; set; }
}