// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoodseatsScouts.Coins.Api.Data;

#nullable disable

namespace WoodseatsScouts.Coins.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424224114_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ActivityBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityBases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Archery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Abseiling"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aerial Trek"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aeroball"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bouldering"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bushcraft"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Campfire"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Canoeing"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Caving"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fencing"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hike"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hillwalking"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Kayaking"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Orienteering"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pioneering"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Powerboating"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Raft Building"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sailing"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tomahawk throwing"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Zip wire"
                        },
                        new
                        {
                            Id = 21,
                            Name = "46th St Pauls"
                        },
                        new
                        {
                            Id = 22,
                            Name = "146th Old Norton"
                        },
                        new
                        {
                            Id = 23,
                            Name = "173rd Woodhouse"
                        },
                        new
                        {
                            Id = 24,
                            Name = "186th Manor"
                        },
                        new
                        {
                            Id = 25,
                            Name = "219th Stradbroke"
                        },
                        new
                        {
                            Id = 26,
                            Name = "229th Greenhill"
                        },
                        new
                        {
                            Id = 27,
                            Name = "246th Beauchief"
                        },
                        new
                        {
                            Id = 28,
                            Name = "270th Intake"
                        },
                        new
                        {
                            Id = 29,
                            Name = "273rd Handsworth"
                        },
                        new
                        {
                            Id = 31,
                            Name = "280th Norton"
                        },
                        new
                        {
                            Id = 32,
                            Name = "297th Bradway"
                        },
                        new
                        {
                            Id = 33,
                            Name = "49th Beighton"
                        },
                        new
                        {
                            Id = 34,
                            Name = "69th Mosborough"
                        },
                        new
                        {
                            Id = 35,
                            Name = "74th Oak Street"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Misc"
                        });
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityBaseId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityBaseSequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComputedColumnSql("'C' + (FORMAT([ActivityBaseSequenceNumber], '0000'))  + (FORMAT([ActivityBaseId], '000')) + (FORMAT([Value], '000'))");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityBaseId");

                    b.HasIndex("MemberId");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScanCoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinId")
                        .HasColumnType("int");

                    b.Property<int>("ScanSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.HasIndex("ScanSessionId");

                    b.ToTable("ScanCoins");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScanSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScoutMemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScoutMemberId");

                    b.ToTable("ScanSessions");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScoutGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScoutGroups");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScoutMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clue1State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Clue2State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Clue3State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("'M' + (FORMAT(ScoutGroupId, '000'))  + [ScoutSectionId] + (FORMAT(Number, '000'))");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDayVisitor")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ScoutGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ScoutSectionId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("ScoutGroupId");

                    b.HasIndex("ScoutSectionId");

                    b.ToTable("ScoutMembers");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScoutSection", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ScoutSections");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Coin", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ActivityBase", "ActivityBase")
                        .WithMany()
                        .HasForeignKey("ActivityBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ScoutMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.Navigation("ActivityBase");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScanCoin", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ScanSession", "ScanSession")
                        .WithMany("ScanCoins")
                        .HasForeignKey("ScanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");

                    b.Navigation("ScanSession");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScanSession", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ScoutMember", "ScoutMember")
                        .WithMany("ScavengeResults")
                        .HasForeignKey("ScoutMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoutMember");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScoutMember", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ScoutGroup", "ScoutGroup")
                        .WithMany("ScoutMembers")
                        .HasForeignKey("ScoutGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ScoutSection", "ScoutSection")
                        .WithMany()
                        .HasForeignKey("ScoutSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoutGroup");

                    b.Navigation("ScoutSection");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScanSession", b =>
                {
                    b.Navigation("ScanCoins");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScoutGroup", b =>
                {
                    b.Navigation("ScoutMembers");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScoutMember", b =>
                {
                    b.Navigation("ScavengeResults");
                });
#pragma warning restore 612, 618
        }
    }
}
