// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoodseatsScouts.Coins.Api.Data;

#nullable disable

namespace WoodseatsScouts.Coins.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419150441_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ActivityBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityBases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Archery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Abseiling"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aerial Trek"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aeroball"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bouldering"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bushcraft"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Campfire"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Canoeing"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Caving"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fencing"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hike"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hillwalking"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Kayaking"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Orienteering"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pioneering"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Powerboating"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Raft Building"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sailing"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tomahawk throwing"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Zip wire"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Misc"
                        });
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityBaseId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityBaseSequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasComputedColumnSql("'C' + (FORMAT([ActivityBaseSequenceNumber], '0000'))  + (FORMAT([ActivityBaseId], '000')) + (FORMAT([Value], '000'))");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityBaseId");

                    b.HasIndex("MemberId");

                    b.ToTable("Coins");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clue1State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clue2State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clue3State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("'M' + (FORMAT(TroopId, '000'))  + [SectionId] + (FORMAT(Number, '000'))");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDayVisitor")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("TroopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("TroopId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("ScavengeResults");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengedCoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<int>("ScavengeResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScavengeResultId");

                    b.ToTable("ScavengedCoins");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Section", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Troop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Troops");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Coin", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ActivityBase", "ActivityBase")
                        .WithMany()
                        .HasForeignKey("ActivityBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.Navigation("ActivityBase");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Member", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Troop", "Troop")
                        .WithMany("Members")
                        .HasForeignKey("TroopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Troop");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengeResult", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Member", "Member")
                        .WithMany("ScavengeResults")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengedCoin", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ScavengeResult", "ScavengeResult")
                        .WithMany("ScavengedCoins")
                        .HasForeignKey("ScavengeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScavengeResult");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Member", b =>
                {
                    b.Navigation("ScavengeResults");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengeResult", b =>
                {
                    b.Navigation("ScavengedCoins");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Troop", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
