// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoodseatsScouts.Coins.Api.Data;

#nullable disable

namespace WoodseatsScouts.Coins.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Coin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Base")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base = 2,
                            Code = "B0002002003",
                            Value = 3
                        },
                        new
                        {
                            Id = 2,
                            Base = 3,
                            Code = "B0003003009",
                            Value = 9
                        },
                        new
                        {
                            Id = 3,
                            Base = 1,
                            Code = "B0004001010",
                            Value = 10
                        },
                        new
                        {
                            Id = 4,
                            Base = 2,
                            Code = "B0005002011",
                            Value = 11
                        },
                        new
                        {
                            Id = 5,
                            Base = 3,
                            Code = "B0006003020",
                            Value = 20
                        },
                        new
                        {
                            Id = 6,
                            Base = 1,
                            Code = "B0007001003",
                            Value = 3
                        },
                        new
                        {
                            Id = 7,
                            Base = 2,
                            Code = "B0008002009",
                            Value = 9
                        },
                        new
                        {
                            Id = 8,
                            Base = 3,
                            Code = "B0009003010",
                            Value = 10
                        },
                        new
                        {
                            Id = 9,
                            Base = 1,
                            Code = "B0010001011",
                            Value = 11
                        },
                        new
                        {
                            Id = 10,
                            Base = 2,
                            Code = "B0011002020",
                            Value = 20
                        },
                        new
                        {
                            Id = 11,
                            Base = 3,
                            Code = "B0012003003",
                            Value = 3
                        },
                        new
                        {
                            Id = 12,
                            Base = 1,
                            Code = "B0013001009",
                            Value = 9
                        },
                        new
                        {
                            Id = 13,
                            Base = 2,
                            Code = "B0014002010",
                            Value = 10
                        },
                        new
                        {
                            Id = 14,
                            Base = 3,
                            Code = "B0015003011",
                            Value = 11
                        },
                        new
                        {
                            Id = 15,
                            Base = 1,
                            Code = "B0016001020",
                            Value = 20
                        },
                        new
                        {
                            Id = 16,
                            Base = 2,
                            Code = "B0017002003",
                            Value = 3
                        },
                        new
                        {
                            Id = 17,
                            Base = 3,
                            Code = "B0018003009",
                            Value = 9
                        },
                        new
                        {
                            Id = 18,
                            Base = 1,
                            Code = "B0019001010",
                            Value = 10
                        },
                        new
                        {
                            Id = 19,
                            Base = 2,
                            Code = "B0020002011",
                            Value = 11
                        },
                        new
                        {
                            Id = 20,
                            Base = 3,
                            Code = "B0021003020",
                            Value = 20
                        },
                        new
                        {
                            Id = 21,
                            Base = 1,
                            Code = "B0022001003",
                            Value = 3
                        },
                        new
                        {
                            Id = 22,
                            Base = 2,
                            Code = "B0023002009",
                            Value = 9
                        },
                        new
                        {
                            Id = 23,
                            Base = 3,
                            Code = "B0024003010",
                            Value = 10
                        },
                        new
                        {
                            Id = 24,
                            Base = 1,
                            Code = "B0025001011",
                            Value = 11
                        },
                        new
                        {
                            Id = 25,
                            Base = 2,
                            Code = "B0026002020",
                            Value = 20
                        },
                        new
                        {
                            Id = 26,
                            Base = 3,
                            Code = "B0027003003",
                            Value = 3
                        },
                        new
                        {
                            Id = 27,
                            Base = 1,
                            Code = "B0028001009",
                            Value = 9
                        },
                        new
                        {
                            Id = 28,
                            Base = 2,
                            Code = "B0029002010",
                            Value = 10
                        },
                        new
                        {
                            Id = 29,
                            Base = 3,
                            Code = "B0030003011",
                            Value = 11
                        },
                        new
                        {
                            Id = 30,
                            Base = 1,
                            Code = "B0031001020",
                            Value = 20
                        },
                        new
                        {
                            Id = 31,
                            Base = 2,
                            Code = "B0032002003",
                            Value = 3
                        },
                        new
                        {
                            Id = 32,
                            Base = 3,
                            Code = "B0033003009",
                            Value = 9
                        },
                        new
                        {
                            Id = 33,
                            Base = 1,
                            Code = "B0034001010",
                            Value = 10
                        },
                        new
                        {
                            Id = 34,
                            Base = 2,
                            Code = "B0035002011",
                            Value = 11
                        },
                        new
                        {
                            Id = 35,
                            Base = 3,
                            Code = "B0036003020",
                            Value = 20
                        },
                        new
                        {
                            Id = 36,
                            Base = 1,
                            Code = "B0037001003",
                            Value = 3
                        },
                        new
                        {
                            Id = 37,
                            Base = 2,
                            Code = "B0038002009",
                            Value = 9
                        },
                        new
                        {
                            Id = 38,
                            Base = 3,
                            Code = "B0039003010",
                            Value = 10
                        },
                        new
                        {
                            Id = 39,
                            Base = 1,
                            Code = "B0040001011",
                            Value = 11
                        },
                        new
                        {
                            Id = 40,
                            Base = 2,
                            Code = "B0041002020",
                            Value = 20
                        },
                        new
                        {
                            Id = 41,
                            Base = 3,
                            Code = "B0042003003",
                            Value = 3
                        },
                        new
                        {
                            Id = 42,
                            Base = 1,
                            Code = "B0043001009",
                            Value = 9
                        },
                        new
                        {
                            Id = 43,
                            Base = 2,
                            Code = "B0044002010",
                            Value = 10
                        },
                        new
                        {
                            Id = 44,
                            Base = 3,
                            Code = "B0045003011",
                            Value = 11
                        },
                        new
                        {
                            Id = 45,
                            Base = 1,
                            Code = "B0046001020",
                            Value = 20
                        },
                        new
                        {
                            Id = 46,
                            Base = 2,
                            Code = "B0047002003",
                            Value = 3
                        },
                        new
                        {
                            Id = 47,
                            Base = 3,
                            Code = "B0048003009",
                            Value = 9
                        },
                        new
                        {
                            Id = 48,
                            Base = 1,
                            Code = "B0049001010",
                            Value = 10
                        },
                        new
                        {
                            Id = 49,
                            Base = 2,
                            Code = "B0050002011",
                            Value = 11
                        },
                        new
                        {
                            Id = 50,
                            Base = 3,
                            Code = "B0051003020",
                            Value = 20
                        });
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Clue1State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clue2State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clue3State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("'M' + (FORMAT(TroopId, '000'))  + [SectionId] + (FORMAT(Number, '000'))");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDayVisitor")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("TroopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("TroopId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Crimson",
                            HasImage = true,
                            IsDayVisitor = false,
                            LastName = "Charcoal",
                            Number = 0,
                            SectionId = "A",
                            TroopId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Glaucous",
                            HasImage = true,
                            IsDayVisitor = false,
                            LastName = "Jet",
                            Number = 0,
                            SectionId = "B",
                            TroopId = 2
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Saffron",
                            HasImage = true,
                            IsDayVisitor = false,
                            LastName = "Hunter",
                            Number = 0,
                            SectionId = "C",
                            TroopId = 3
                        });
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengedCoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<int>("ScavengeResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScavengeResultId");

                    b.ToTable("ScavengedCoins");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengeResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("ScavengeResults");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Section", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Code = "B",
                            Name = "Beavers"
                        },
                        new
                        {
                            Code = "C",
                            Name = "Cubs"
                        },
                        new
                        {
                            Code = "E",
                            Name = "Explorers"
                        },
                        new
                        {
                            Code = "A",
                            Name = "Adults"
                        },
                        new
                        {
                            Code = "S",
                            Name = "Scouts"
                        });
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Troop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Troops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Charcoal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hunter"
                        });
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Coin", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Member", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Troop", "Troop")
                        .WithMany("Members")
                        .HasForeignKey("TroopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Troop");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengedCoin", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.ScavengeResult", "ScavengeResult")
                        .WithMany("ScavengedCoins")
                        .HasForeignKey("ScavengeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScavengeResult");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengeResult", b =>
                {
                    b.HasOne("WoodseatsScouts.Coins.Api.Models.Domain.Member", "Member")
                        .WithMany("ScavengeResults")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Member", b =>
                {
                    b.Navigation("ScavengeResults");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.ScavengeResult", b =>
                {
                    b.Navigation("ScavengedCoins");
                });

            modelBuilder.Entity("WoodseatsScouts.Coins.Api.Models.Domain.Troop", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
